jobs:
- job: Default
  timeoutInMinutes: 60
  pool:
    vmImage: Ubuntu-16.04
  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH
  - bash: conda create --yes --quiet --name kinesis python=3.7 pip
    displayName: Create Anaconda environment
  - bash: |
      source activate kinesis
      # may include this to setup.py in the end
      pip install pandas
      pip install git+https://github.com/smoh/gapipes.git@master
      cd $(Build.SourcesDirectory)
      pip install -e .
      pip freeze | grep -E "astropy|kinesis|pystan|arviz"
    displayName: Install dependencies
  - bash: |
      source activate kinesis
      pip install pytest
      pytest .
    displayName: Run tests

- job: build_and_publish_docs
  timeoutInMinutes: 60
  pool:
    vmImage: Ubuntu-16.04
  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH
  - bash: conda create --yes --quiet --name kinesis python=3.7 pip
    displayName: Create Anaconda environment
  - bash: |
      source activate kinesis
      # may include this to setup.py in the end
      pip install pandas
      pip install git+https://github.com/smoh/gapipes.git@master
      cd $(Build.SourcesDirectory)
      pip install -e .
      pip freeze | grep -E "astropy|kinesis|pystan|arviz"
    displayName: Install dependencies
  - bash: |
      pip install sphinx
      pip install -U -r docs/requirements.txt
    displayName: Install docs dependencies
  - bash: |
      make html
      workingDirectory: docs/
    displayName: Build html docs
  - bash: |
      mkdir ghpages
      git clone -b gh-pages --single-branch https://github.com/smoh/kinesis-dev.git .
      rm -rf .git
      mv docs/_build/html/* .
      git init
      git add -f *
      touch .nojekyll
      git add .nojekyll
      git commit -m 'Build gh-pages'
      git push -f https://github.com/smoh/kinesis-dev HEAD:gh-pages
    displayName: Push to gh-pages
